# 📘 CH06. NumPy & Pandas — 강의용 노트북 (확장판)

━━━━━━━━━━━━━━━━

> 이 노트북은 **CH06-02(NumPy) → CH06-03(Pandas)** 순서로 진행됩니다.
> (CH06-01 데이터 분석 개요는 별도 자료로 진행)
>
> 🕐 **정규 수업**: 개념 설명 + 예시 라이브 코딩 중심

> 🌙 **자율 멘토링**: 각 챕터 끝의 💻 실습(TODO)과 📝 실습 과제를 직접 풀어봅니다.


# 📘 CH06-02. NumPy

## 🤔 먼저 생각해보기

> **일주일치 애플(AAPL) 주가에서 하루 만에 평균 대비 얼마나 오르내렸는지 한 번에 계산하려면 어떻게 해야 할까요?**

리스트로 하나하나 반복문을 돌리는 것보다 훨씬 빠르고 간결하게, 배열 전체에 통계 계산이나 연산을 한 번에 적용할 수 있는 도구가 **NumPy**입니다.
오늘 수업이 끝나면 "반복문 없이" 아래와 같은 질문에 답할 수 있게 됩니다.

- 5일치 주가 전체에 수수료 1.5%를 한 줄로 적용하려면?
- 일주일 중 **며칠째**가 최고가였는지 찾으려면?
- 평균보다 높았던 날만 골라내려면?


## 📖 핵심 개념

### 1) NumPy란? — 숫자 배열을 위한 핵심 라이브러리

- 파이썬에서 **수치 계산의 표준** 라이브러리입니다.
- 핵심 자료구조는 `ndarray`(N-dimensional array, N차원 배열)입니다.
- 다음 시간부터 쓸 Pandas도 내부적으로는 NumPy 배열 위에서 동작합니다. 오늘 배우는 원리가 그대로 Pandas의 원리가 됩니다.


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
import numpy as np   # 관례적으로 np라는 별칭을 사용

prices = np.array([189.5, 191.2, 187.8, 193.4, 195.9])   # 애플 주가 (5일치)
print(prices)
print(type(prices))   # <class 'numpy.ndarray'>
```

</details>

In [ ]:
# numpy 불러오기
# 관례적으로 np라는 별칭을 사용
import numpy as np

# 애플 주가 5일치
prices = np.array([189.5, 191.2, 187.8, 193.4, 195.9])
print(prices)
print(type(prices))


[189.5 191.2 187.8 193.4 195.9]
<class 'numpy.ndarray'>


표현 방식
- 리스트: [1, 2, 3]
- adarray: [1 2 3]

> NumPy는 ndarray를 수학의 행렬처럼   출력하기 위해 콤마를 생략해서 보여줍니다. 실제 데이터가 없는 것이 아니라, 출력 형식만 다를 뿐입니다.

### 2) 배열 생성하기

배열을 만드는 방법은 여러 가지입니다. 가장 기본은 **리스트를 `np.array()`에 넣는 것**입니다.


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 1: 리스트로부터 생성 — 주가
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
```

</details>

In [ ]:
# 예시 1: 리스트로부터 생성

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)


[1 2 3 4 5]


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 2: 카페 일주일 판매량으로도 만들어봅시다
sales = np.array([120, 135, 98, 150, 210, 260, 240])   # 월~일 판매잔수
print(sales)
```

</details>

In [ ]:
# 예시 2: 카페 일주일 판매량으로도 만들어봅시다
# 월~일 판매잔수
sales = np.array([120, 135, 98, 150, 210, 260, 240])
print(sales)


[120 135  98 150 210 260 240]


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 3: 2차원 배열 (행렬) — 3개 종목 x 3일치 종가
prices_2d = np.array([
    [135.58, 137.71, 140.15],   # 엔비디아
    [189.51, 191.20, 193.42],   # 애플
    [248.50, 251.30, 245.10]    # 테슬라
])
print(prices_2d)
```

</details>

In [ ]:
# 예시 3: 2차원 배열 (행렬) — 3개 종목 x 3일치 종가

prices_2d = np.array([
    [135.58, 137.71, 140.15],
    [189.51, 191.20, 193.43],
    [248.50, 251.30, 245.10]
])
print(prices_2d)


[[135.58 137.71 140.15]
 [189.51 191.2  193.43]
 [248.5  251.3  245.1 ]]


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 4: 학생 3명 x 과목 3개 점수표도 똑같은 원리
scores = np.array([
    [90, 85, 77],   # 김민준: 국어, 영어, 수학
    [65, 95, 88],   # 이서연
    [72, 60, 94]    # 박지훈
])
print(scores)
```

</details>

In [ ]:
# 예시 4: 학생 3명 x 과목 3개 점수표도 똑같은 원리

scores = np.array([
    # 국 영 수
    [90, 85, 77],   # 학생 1
    [65, 95, 88],   # 학생 2
    [72, 60, 94]    # 학생 3
])
print(scores)


[[90 85 77]
 [65 95 88]
 [72 60 94]]


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 특수한 배열 생성 함수들
zeros = np.zeros(5)          # 0으로 채워진 배열
print(zeros)                 # [0. 0. 0. 0. 0.]

ones = np.ones((2, 3))       # 1로 채워진 2행 3열 배열
print(ones)

arr2 = np.arange(0, 10, 2)   # range와 유사 (시작, 끝, 간격)
print(arr2)                  # [0 2 4 6 8]

arr3 = np.linspace(0, 1, 5)  # 0부터 1까지 5개로 균등 분할
print(arr3)                  # [0.   0.25 0.5  0.75 1.  ]
```

</details>

In [ ]:
# 특수한 배열 생성 함수들

# 0으로 채워진 배열
zeros = np.zeros(5)
print(zeros)


# 1로 채워진 2행 3열 배열
ones = np.ones((2, 3))
print(ones)

# arange - range와 유사 (시작, 끝, 간격)
arr2 = np.arange(0,10,2)
print(arr2)

# 0부터 1까지 5개로 균등 분할
# Linear Space
arr3 = np.linspace(0,1,5)
print(arr3)



[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


**중요한 성질 — 배열은 "한 가지 자료형만" 담습니다**

리스트는 숫자·문자를 섞을 수 있지만, NumPy 배열은 **모든 값이 같은 자료형**이어야 합니다.
섞어서 넣으면 어떻게 되는지 직접 확인해봅시다.


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 정수와 실수를 섞으면? → 전부 실수(float)로 통일됨
mixed1 = np.array([1, 2, 3.5])
print(mixed1)         # [1.  2.  3.5]
print(mixed1.dtype)   # float64
```

</details>

In [ ]:
# 정수와 실수를 섞으면? → 전부 실수(float)로 통일됨

mixed1 = np.array([1, 2, 3.5])
print(mixed1)
print(mixed1.dtype)

print(type(mixed1))

[1.  2.  3.5]
float64
<class 'numpy.ndarray'>


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 숫자와 문자를 섞으면? → 전부 문자열로 통일됨 (계산 불가능해짐!)
mixed2 = np.array([1, 2, "삼"])
print(mixed2)         # ['1' '2' '삼']
print(mixed2.dtype)   # <U... (유니코드 문자열)

# print(mixed2 + 10)  # ❌ 문자열이 되어버려서 숫자 연산 불가
```

</details>

In [ ]:
# 숫자와 문자를 섞으면? → 전부 문자열로 통일됨 (계산 불가능해짐!)

mixed2 = np.array([1, 2, "삼"])
print(mixed2)
print(mixed2.dtype) # 유니코드 문자열


['1' '2' '삼']
<U21


> 💡 이 "동일 자료형" 제약 덕분에 NumPy는 리스트보다 훨씬 빠릅니다. 자유를 조금 포기하고 속도를 얻은 셈입니다.

### 3) 배열의 주요 속성

배열을 받으면 가장 먼저 **모양(shape)** 부터 확인하는 습관을 들입시다.


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
prices_2d = np.array([
    [135.58, 137.71, 140.15],
    [189.51, 191.20, 193.42],
    [248.50, 251.30, 245.10]
])

print(prices_2d.shape)   # (3, 3)  — 3행 3열
print(prices_2d.ndim)    # 2       — 2차원
print(prices_2d.dtype)   # float64 — 저장된 값의 자료형
print(prices_2d.size)    # 9       — 전체 요소 개수
```

</details>

In [ ]:
# 코드 입력

prices_2d = np.array([
    [135.58, 137.71, 140.15],
    [189.51, 191.20, 193.42],
    [248.50, 251.30, 245.10]
])

# 모양은?
print(prices_2d.shape)

# 차원은?
print(prices_2d.ndim)

# 배열에 저장된 값의 자료형은?
print(prices_2d.dtype)

# 전체 요소 개수는?
print(prices_2d.size)


(3, 3)
2
float64
9


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 1차원 배열의 속성과 비교해보기
sales = np.array([120, 135, 98, 150, 210, 260, 240])
print(sales.shape)   # (7,)  — 7개짜리 1차원 (콤마 뒤가 비어있음에 주목!)
print(sales.ndim)    # 1
print(sales.size)    # 7
```

</details>

In [ ]:
# 1차원 배열의 속성과 비교해보기

sales = np.array([120, 135, 98, 150, 210, 260, 240])
print(sales.shape)  # () 안에 숫자 개수가 차원 수와 동일. 숫자가 하나면 1차원
print(sales.ndim)
print(sales.size)




(7,)
1
7


> 💡 `(7,)`과 `(7, 1)`은 다릅니다. 앞은 1차원, 뒤는 "7행 1열의 2차원"입니다. shape의 괄호 안 숫자 개수 = 차원 수라고 기억하세요.

### 4) 인덱싱과 슬라이싱

리스트에서 배운 `[ ]` 문법이 그대로 통합니다. 다양한 상황으로 손에 익혀봅시다.


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 1: 주가에서 특정 날짜 꺼내기
prices = np.array([189.5, 191.2, 187.8, 193.4, 195.9])

print(prices[0])     # 189.5  (첫째 날 종가)
print(prices[-1])    # 195.9  (마지막 날 종가)
print(prices[1:4])   # [191.2 187.8 193.4]  (2~4일차)
```

</details>

In [ ]:
# 예시 1: 주가에서 특정 날짜 꺼내기

prices = np.array([189.5, 191.2, 187.8, 193.4, 195.9])

print(prices[0])
print(prices[-1])
print(prices[1:4])


189.5
195.9
[191.2 187.8 193.4]


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 2: 카페 판매량에서 주말만/평일만 잘라내기 (월~일 순서)
sales = np.array([120, 135, 98, 150, 210, 260, 240])

print(sales[5:])     # [260 240]           — 주말(토, 일)
print(sales[:5])     # [120 135  98 150 210] — 평일(월~금)
print(sales[::2])    # [120  98 210 240]   — 하루 걸러 하나씩
```

</details>

In [ ]:
# 예시 2: 카페 판매량에서 주말만/평일만 잘라내기 (월~일 순서)

sales = np.array([120, 135, 98, 150, 210, 260, 240])

print(sales[5:])
print(sales[:5])
print(sales[::2])


[260 240]
[120 135  98 150 210]
[120  98 210 240]


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 3: 2차원 배열 인덱싱 — [행, 열]
prices_2d = np.array([
    [135.58, 137.71, 140.15],   # 엔비디아
    [189.51, 191.20, 193.42],   # 애플
    [248.50, 251.30, 245.10]    # 테슬라
])

print(prices_2d[0])        # [135.58 137.71 140.15]  (엔비디아 전체)
print(prices_2d[1, 2])     # 193.42  (애플의 3일차 종가)
print(prices_2d[:, 0])     # [135.58 189.51 248.5 ]  (모든 종목의 1일차 종가)
print(prices_2d[0:2, 1:3]) # 엔비디아·애플의 2~3일차
```

</details>

In [ ]:
# 예시 3: 2차원 배열 인덱싱 — [행, 열]

prices_2d = np.array([
    [135.58, 137.71, 140.15],   # 엔비디아
    [189.51, 191.20, 193.42],   # 애플
    [248.50, 251.30, 245.10]    # 테슬라
])

print(prices_2d[0])
print(prices_2d[1,2])
print(prices_2d[:,0])   # 전체 중에서 0번째
print(prices_2d[0:2,1:3])   # 엔비디아, 애플의 2-3일차 종가


[135.58 137.71 140.15]
193.42
[135.58 189.51 248.5 ]
[[137.71 140.15]
 [191.2  193.42]]


> prices_2d[1][2]도 가능합니다. 하지만 NumPy에서는 prices_2d[1, 2]처럼 한 번에 인덱싱하는 방식을 권장합니다. 더 빠르고, 차원이 높아져도 일관되게 사용할 수 있기 때문입니다.

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 4: 성적표에서 원하는 부분만 — 같은 문법, 다른 데이터
scores = np.array([
    [90, 85, 77],   # 김민준
    [65, 95, 88],   # 이서연
    [72, 60, 94]    # 박지훈
])

print(scores[1])       # 이서연의 전 과목 점수
print(scores[1, 0])    # 이서연의 국어 점수 (65)
print(scores[:, 2])    # 전원의 수학 점수 [77 88 94]
print(scores[:2, :2])  # 앞 두 학생의 국어·영어만
```

</details>

In [ ]:
# 예시 4: 성적표에서 원하는 부분만 — 같은 문법, 다른 데이터
# 국어, 수학, 영어

scores = np.array([
    [90, 85, 77],   # 김민준
    [65, 95, 88],   # 이서연
    [72, 60, 94]    # 박지훈
])

# 이서연의 전과목 점수
print(scores[1])

# 이서연의 국어 점수
print(scores[1,0])

# 전원 수학 점수
print(scores[:,1])

# 앞 두 학생의 국어, 수학 점수
print(scores[:2, :2])

# 앞 두 학생의 국어, 영어 점수
print(scores[:2,::2])


[65 95 88]
65
[85 95 60]
[[90 85]
 [65 95]]
[[90 77]
 [65 88]]


> 💡 `[행, 열]`에서 `:` 하나만 있으면 "전부"라는 뜻입니다. `[:, 2]` = "행은 전부, 열은 2번" = "3번째 열 전체".


### 5) 배열 연산 — 값 전체에 한 번에 적용 (브로드캐스팅)

NumPy의 진짜 매력이 여기서 시작됩니다. **배열 전체에 연산자를 그대로 적용**할 수 있습니다.
반복문이 사라지는 순간을 여러 상황으로 체험해봅시다.

> 브로드캐스팅(Broadcasting)은 크기가 다른 배열도 NumPy가 자동으로 크기를 맞춰 계산해 주는 기능입니다.


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 1: 주가 전체에 한 번에 계산
prices = np.array([189.5, 191.2, 187.8, 193.4, 195.9])

print(prices + 10)              # 모든 값에 10 더하기
print(prices * 1.1)             # 모든 값에 10% 가산 (수수료 계산 등)
print(prices - prices.mean())   # 평균과의 차이 (편차)
```

</details>

In [ ]:
# 예시 1: 주가 전체에 한 번에 계산

prices = np.array([189.5, 191.2, 187.8, 193.4, 195.9])

print(prices + 10)
print(prices * 1.1)

# 평균과의 차이(편차)
print(prices - prices.mean())

# 평균 mean()
print(prices.mean())

[199.5 201.2 197.8 203.4 205.9]
[208.45 210.32 206.58 212.74 215.49]
[-2.06 -0.36 -3.76  1.84  4.34]
191.56


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 2: 환율 적용 — 달러 주가를 원화로 (1달러 = 1,490원 가정)
prices_usd = np.array([189.5, 191.2, 187.8])
prices_krw = prices_usd * 1490
print(prices_krw)   # 한 줄로 전체 환산 끝
```

</details>

In [ ]:
# 예시 2: 환율 적용 — 달러 주가를 원화로 (1달러 = 1,490원 가정)

prices_usd = np.array([189.5, 191.2, 187.8])
prices_krw = prices_usd * 1490
print(prices_krw)


[282355. 284888. 279822.]


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 3: 온도 변환 — 화씨(°F) 일주일치를 섭씨(°C)로
temps_f = np.array([68, 72, 75, 71, 66, 80, 77])
temps_c = (temps_f - 32) * 5 / 9
print(temps_c.round(1))   # round(1): 소수점 1자리 반올림
```

</details>

In [ ]:
# 예시 3: 온도 변환 — 화씨(°F) 일주일치를 섭씨(°C)로
# 화씨 > 섭씨 공식 (°C = (°F - 32) * 5/9

temps_f = np.array([68, 72, 75, 71, 66, 80, 77])
temps_c = (temps_f - 32) * 5 / 9

# numpy에서는 round()가 아니라 .round()로 쓴다.
print(temps_c.round(2))


[20.   22.22 23.89 21.67 18.89 26.67 25.  ]


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 4: 할인가 계산 — 정가 배열에 20% 할인 일괄 적용
price_list = np.array([12000, 4500, 33000, 8900])
sale_price = price_list * 0.8
print(sale_price)
```

</details>

In [ ]:
# 예시 4: 할인가 계산 — 정가 배열에 20% 할인 일괄 적용

price_list = np.array([12000, 4500, 33000, 8900])
sale_price = price_list * 0.8
print(sale_price)


[ 9600.  3600. 26400.  7120.]


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 배열끼리도 같은 위치끼리 자동으로 계산됨
apple = np.array([189.5, 191.2, 187.8])
tesla = np.array([248.5, 251.3, 245.1])

print(apple + tesla)    # 같은 날짜끼리 더함
print(tesla - apple)    # 같은 날짜끼리 차이 계산
```

</details>

In [ ]:
# 배열끼리도 같은 위치끼리 자동으로 계산됨

apple = np.array([189.5, 191.2, 187.8])
tesla = np.array([248.5, 251.3, 245.1])

print(apple + tesla)
print(tesla - apple)


[438.  442.5 432.9]
[59.  60.1 57.3]


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 5: 배열끼리 연산 실전 — 매출액 = 가격 x 판매량
menu_price = np.array([4500, 5000, 5500])     # 아메리카노, 라떼, 콜드브루
menu_qty   = np.array([120, 80, 45])          # 판매잔수

revenue = menu_price * menu_qty               # 같은 위치끼리 곱
print(revenue)                                # [540000 400000 247500]
print(revenue.sum())                          # 총매출
```

</details>

In [ ]:
# 예시 5: 배열끼리 연산 실전 — 매출액 = 가격 x 판매량

menu_price = np.array([4500, 5000, 5500])     # 가격
menu_qty   = np.array([120, 80, 45])          # 판매량

revenue = menu_price * menu_qty
print('메뉴별 매출액:', revenue)
print('총 매출액:', revenue.sum())


메뉴별 매출액: [540000 400000 247500]
총 매출액: 1187500


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 6: 수익률(%) 계산 — (오늘 - 어제) / 어제 * 100
today     = np.array([191.2, 251.3, 137.71])
yesterday = np.array([189.5, 248.5, 135.58])

change_pct = (today - yesterday) / yesterday * 100
print(change_pct.round(2))   # 종목별 등락률(%)이 한 줄에
```

</details>

In [ ]:
# 예시 6: 수익률(%) 계산 — (오늘 - 어제) / 어제 * 100

today     = np.array([191.2, 251.3, 137.71])
yesterday = np.array([189.5, 248.5, 135.58])

change_pct = (today - yesterday) / yesterday * 100
print(change_pct)

[0.89709763 1.12676056 1.57102818]


> 💡 방금 한 "가격 x 판매량", "등락률 계산"은 다음 시간부터 Pandas에서 `df["가격"] * df["판매량"]` 형태로 똑같이 다시 만납니다. 원리는 오늘 이미 배운 것입니다.

### 6) 통계 함수

배열이 스스로 통계를 계산해줍니다. 여기에 **"위치를 찾아주는" 함수**까지 더하면 실전 질문에 답할 수 있습니다.


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
prices = np.array([189.5, 191.2, 187.8, 193.4, 195.9])

print(prices.mean())   # 평균: 191.56
print(prices.sum())    # 합계
print(prices.max())    # 최댓값
print(prices.min())    # 최솟값
print(prices.std())    # 표준편차 (변동성 측정에 활용)
```

</details>

In [ ]:
# 코드 입력

prices = np.array([189.5, 191.2, 187.8, 193.4, 195.9])

print(prices.mean()) # 평균
print(prices.sum())  # 합계
print(prices.max())  # 최댓값
print(prices.min())  # 최솟값
print(prices.std())  # 표준편차

191.56
957.8
195.9
187.8
2.8541899025818163


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# "값"이 아니라 "위치"가 궁금할 때 — argmax / argmin
prices = np.array([189.5, 191.2, 187.8, 193.4, 195.9])

print(prices.argmax())   # 4  → 5일차(인덱스 4)가 최고가였다!
print(prices.argmin())   # 2  → 3일차가 최저가

# 실전 질문: "일주일 중 언제 제일 많이 팔렸나?"
sales = np.array([120, 135, 98, 150, 210, 260, 240])
days = ["월", "화", "수", "목", "금", "토", "일"]
best = sales.argmax()
print(f"가장 많이 팔린 요일: {days[best]}요일 ({sales[best]}잔)")
```

</details>

In [ ]:
# "값"이 아니라 "위치"가 궁금할 때 — argmax / argmin
prices = np.array([189.5, 191.2, 187.8, 193.4, 195.9])

print(prices.max())     # 최대값
print(prices.argmax())  # 최대값 인덱스
print(prices.min())     # 최소값
print(prices.argmin())  # 최소값 인덱스


195.9
4
187.8
2


In [ ]:
# 실전 질문: "일주일 중 언제 제일 많이 팔렸나?"
sales = np.array([120, 135, 98, 150, 210, 260, 240])
days = ["월", "화", "수", "목", "금", "토", "일"]

best = sales.argmax() # 최대값 인덱스
best
print(f"가장 많이 팔린 요일: {days[best]}요일 ({sales[best]}잔)")

가장 많이 팔린 요일: 토요일 (260잔)


> 💡 `max()`는 "얼마나"에 답하고, `argmax()`는 "언제/어디서"에 답합니다. 분석에서는 후자가 더 중요한 질문일 때가 많습니다.

### 7) axis 정복 — 2차원 배열의 통계는 "방향"이 절반입니다

2차원 배열에서 `mean()`을 그냥 부르면 **전체 평균** 하나만 나옵니다.
"종목별 평균" 또는 "날짜별 평균"을 원한다면 **axis(축)** 를 지정해야 합니다. 초급자가 가장 많이 헷갈리는 지점이니 확실히 잡고 갑시다.

```
axis=0 : ↓ 세로 방향으로 계산 (열별 결과)  → "각 날짜별" 통계
axis=1 : → 가로 방향으로 계산 (행별 결과)  → "각 종목별" 통계
```

암기 팁: **axis는 "없어지는 방향"** 입니다. axis=0이면 행(세로)이 눌려 없어지고 열별 값만 남습니다.


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
prices_2d = np.array([
    [135.58, 137.71, 140.15],   # 엔비디아 (1~3일차)
    [189.51, 191.20, 193.42],   # 애플
    [248.50, 251.30, 245.10]    # 테슬라
])

print(prices_2d.mean())         # 전체 평균 (숫자 하나)
print(prices_2d.mean(axis=1))   # 종목별 평균 (행 방향 →) : 3개
print(prices_2d.mean(axis=0))   # 날짜별 평균 (열 방향 ↓) : 3개
```

</details>

In [ ]:
# 코드 입력
prices_2d = np.array([
    # 1~3일차
    [135.58, 137.71, 140.15],   # 엔비디아
    [189.51, 191.20, 193.42],   # 애플
    [248.50, 251.30, 245.10]    # 테슬라
])

print(prices_2d.mean()) # 전체 평균

# 종목별 평균 (행 방향)
print(prices_2d.mean(axis=1))

# 날짜별 평균 (열 방향)
print(prices_2d.mean(axis=0))

192.49666666666667
[137.81333333 191.37666667 248.3       ]
[191.19666667 193.40333333 192.89      ]


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 같은 원리, 다른 질문 — 성적표로 반복 훈련
scores = np.array([
    [90, 85, 77],   # 김민준 (국, 영, 수)
    [65, 95, 88],   # 이서연
    [72, 60, 94]    # 박지훈
])

print(scores.mean(axis=1))   # 학생별 평균 → [84.  82.67 75.33]
print(scores.mean(axis=0))   # 과목별 평균 → [75.67 80.  86.33]
print(scores.max(axis=1))    # 학생별 최고 점수
print(scores.max(axis=0))    # 과목별 최고 점수
```

</details>

In [ ]:
# 같은 원리, 다른 질문 — 성적표로 반복 훈련

scores = np.array([
    [90, 85, 77],   # 김민준 (국, 영, 수)
    [65, 95, 88],   # 이서연
    [72, 60, 94]    # 박지훈
])

# 학생별 평균
print(scores.mean(axis=1))

# 과목별 평균
print(scores.mean(axis=0))

# 학생별 최고 점수
print(scores.max(axis=1))

# 과목별 최고 점수
print(scores.max(axis=0))


[84.         82.66666667 75.33333333]
[75.66666667 80.         86.33333333]
[90 95 94]
[90 95 94]


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 확인 문제를 코드로 — 결과를 예측한 뒤 실행해보세요!
week_sales = np.array([
    [320, 280, 350],   # 1호점 (금, 토, 일)
    [210, 260, 300],   # 2호점
])

# Q. 지점별 주말 총판매량을 구하려면 axis는 몇일까요?
print(week_sales.sum(axis=1))   # 지점별 합계 → 이게 정답!
print(week_sales.sum(axis=0))   # (비교) 요일별 합계
```

</details>

In [ ]:
# 확인 문제를 코드로 — 결과를 예측한 뒤 실행해보세요!

week_sales = np.array([
    [320, 280, 350],   # 1호점 (금, 토, 일)
    [210, 260, 300],   # 2호점
])

# Q. 지점별 주말 총판매량을 구하려면 axis는 몇일까요?
print(week_sales.sum(axis=1))   # 지점별
print(week_sales.sum(axis=0))   # 요일별


[950 770]
[530 540 650]


### 8) 불리언 인덱싱 — 조건으로 골라내기

배열에 비교 연산을 하면 **True/False 배열**이 나오고, 이것을 대괄호에 넣으면 **True인 값만** 골라집니다.
이 두 단계가 데이터 분석 필터링의 핵심 원리입니다. (다음 시간 Pandas 필터링이 정확히 이 원리로 동작합니다!)


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
prices = np.array([189.5, 191.2, 187.8, 193.4, 195.9])

# 1단계: 비교 연산 → True/False 배열이 생김
mask = prices > 190
print(mask)             # [False  True False  True  True]

# 2단계: 대괄호에 넣으면 True 위치의 값만 남음
print(prices[mask])     # [191.2 193.4 195.9]

# 보통은 한 줄로 합쳐서 씁니다
print(prices[prices > 190])
```

</details>

In [ ]:
# 코드 입력

prices = np.array([189.5, 191.2, 187.8, 193.4, 195.9])

# 1단계: 비교 연산 → True/False 배열이 생김
mask = prices > 190
print(mask)

# 2단계: 대괄호에 넣으면 True 위치의 값만 남음
print(prices[mask])

# 보통은 한 줄로 합쳐서 씁니다
print(prices[prices > 190])

[False  True False  True  True]
[191.2 193.4 195.9]
[191.2 193.4 195.9]


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 1: 평균보다 높았던 날의 주가만
prices = np.array([189.5, 191.2, 187.8, 193.4, 195.9])
print(prices[prices > prices.mean()])
```

</details>

In [ ]:
# 예시 1: 평균보다 높았던 날의 주가만

prices = np.array([189.5, 191.2, 187.8, 193.4, 195.9])

print(prices[prices > prices.mean()])


[193.4 195.9]


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 2: 카페 판매량이 200잔 이상이었던 날은 며칠?
sales = np.array([120, 135, 98, 150, 210, 260, 240])

busy = sales[sales >= 200]
print(busy)              # [210 260 240]
print(len(busy), "일")    # 3일

# True의 개수를 세는 더 간단한 방법 — True=1, False=0이라는 성질 활용
print((sales >= 200).sum(), "일")
```

</details>

In [ ]:
# 예시 2: 카페 판매량이 200잔 이상이었던 날은 며칠?

sales = np.array([120, 135, 98, 150, 210, 260, 240])

busy = sales[sales >= 200]
print(busy)
print(len(busy), "일")


[210 260 240]
3 일


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 3: 조건에 맞는 값들의 통계 — "90점 이상 점수들의 평균"
all_scores = np.array([90, 85, 77, 65, 95, 88, 72, 60, 94])

high = all_scores[all_scores >= 90]
print(high)          # [90 95 94]
print(high.mean())   # 93.0
```

</details>

In [ ]:
# 예시 3: 조건에 맞는 값들의 통계 — "90점 이상 점수들의 평균"

all_scores = np.array([90, 85, 77, 65, 95, 88, 72, 60, 94])

high = all_scores[all_scores >= 90]
print(high.mean())



93.0


> 💡 정리하면: `배열[조건]` = "조건이 True인 값만 남긴다". 다음 시간에 `df[df["급여"] >= 4000]`을 만나면 "아, NumPy에서 배운 그 원리"라고 반가워하시면 됩니다.

### 9) np.where — 조건에 따라 값 바꾸기

`np.where(조건, 참일 때 값, 거짓일 때 값)` — 조건에 따라 **값을 통째로 갈아끼우는** 함수입니다.


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 1: 등락률을 "상승/하락" 라벨로 변환
change = np.array([2.35, -0.87, 1.12, -1.54, 0.33])

labels = np.where(change > 0, "상승", "하락")
print(labels)   # ['상승' '하락' '상승' '하락' '상승']
```

</details>

In [ ]:
# 예시 1: 등락률을 "상승/하락" 라벨로 변환
change = np.array([2.35, -0.87, 1.12, -1.54, 0.33])

labels = np.where(change > 0, '상승', '하락')
print(labels)


['상승' '하락' '상승' '하락' '상승']


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 2: 합격/불합격 판정 (70점 기준)
all_scores = np.array([90, 85, 77, 65, 95, 60])
print(np.where(all_scores >= 70, "합격", "불합격"))
```

</details>

In [ ]:
# 예시 2: 합격/불합격 판정 (70점 기준)

all_scores = np.array([90, 85, 77, 65, 95, 60])

print(np.where(all_scores >= 70, '합격', '불합격'))


['합격' '합격' '합격' '불합격' '합격' '불합격']


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 3: 조건 위치의 "인덱스"를 찾을 수도 있음 (값 2개를 생략하면)
sales = np.array([120, 135, 98, 150, 210, 260, 240])
idx = np.where(sales >= 200)
print(idx)   # (array([4, 5, 6]),)  → 금·토·일 위치
```

</details>

In [ ]:
# 예시 3: 조건 위치의 "인덱스"를 찾을 수도 있음 (값 2개를 생략하면)

sales = np.array([120, 135, 98, 150, 210, 260, 240])

idx = np.where(sales >= 200)
print(idx)



(array([4, 5, 6]),)


- np.where은 항상 튜플을 반환

### 10) 정렬과 모양 바꾸기 — `np.sort()`, `reshape()`


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# np.sort(): 오름차순 정렬 (원본은 그대로, 정렬된 새 배열 반환)
prices = np.array([189.5, 191.2, 187.8, 193.4, 195.9])

print(np.sort(prices))          # 작은 값부터
print(np.sort(prices)[::-1])    # 뒤집으면 내림차순 (큰 값부터)
print(prices)                   # 원본은 그대로!
```

</details>

In [ ]:
# np.sort(): 오름차순 정렬 (원본은 그대로, 정렬된 새 배열 반환)
prices = np.array([189.5, 191.2, 187.8, 193.4, 195.9])

print(np.sort(prices))       # 작은값부터
print(np.sort(prices)[::-1]) # 뒤집으면 내림차순
print(prices)   # 원본은 변경되지 X


[187.8 189.5 191.2 193.4 195.9]
[195.9 193.4 191.2 189.5 187.8]
[189.5 191.2 187.8 193.4 195.9]


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# reshape(): 1차원 <-> 2차원 모양 바꾸기 (요소 개수는 같아야 함)
arr = np.arange(1, 13)          # 1~12
print(arr)

matrix = arr.reshape(3, 4)      # 3행 4열로 재배열
print(matrix)

print(matrix.reshape(-1))       # -1: "알아서 계산" → 다시 1차원으로
```

</details>

In [ ]:
# reshape(): 1차원 <-> 2차원 모양 바꾸기 (요소 개수는 같아야 함)

# 1~12
arr = np.arange(1,13)
print(arr)

# 3행 4열 재배열
matrix1 = arr.reshape(3,4)
print(matrix1)

matrix2 = arr.reshape(6,2)
print(matrix2)

# 다시 1차원으로: -1
print(matrix2.reshape(-1))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


> 💡 `reshape(3, 4)`는 12개짜리를 3x4로. `reshape(5, 4)`는 20개가 필요하므로 에러. **요소 개수가 맞아야** 합니다.

### 11) 서로 다른 방식 비교 — 파이썬 리스트 연산 vs NumPy 배열 연산

같은 작업(모든 값에 10% 더하기)을 두 가지 방식으로 비교해봅시다.


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 방법 A: 파이썬 리스트 (반복문/컴프리헨션 필요)
prices_list = [189.5, 191.2, 187.8, 193.4, 195.9]
result_list = [p * 1.1 for p in prices_list]
print(result_list)
```

</details>

In [ ]:
# 방법 A: 파이썬 리스트 (반복문/컴프리헨션 필요)

prices_list = [189.5, 191.2, 187.8, 193.4, 195.9]

# 반복문
result_list = []
for i in prices_list:
    result_list.append(round(i * 1.1, 2))
print(result_list)

# 컴프리헨션
result_list = [round(p * 1.1, 2) for p in prices_list]
print(result_list)


[208.45, 210.32, 206.58, 212.74, 215.49]
[208.45, 210.32, 206.58, 212.74, 215.49]


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 방법 B: NumPy 배열 (연산자를 그대로 사용)
prices_arr = np.array([189.5, 191.2, 187.8, 193.4, 195.9])
result_arr = prices_arr * 1.1
print(result_arr)
```

</details>

In [ ]:
# 방법 B: NumPy 배열 (연산자를 그대로 사용)

prices_arr = np.array([189.5, 191.2, 187.8, 193.4, 195.9])

result_arr = prices_arr * 1.1
print(result_arr)


[208.45 210.32 206.58 212.74 215.49]


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 리스트끼리 "+"을 하면 이어붙이기(연결)가 되어버림 — 전혀 다른 결과!
list_a = [1, 2, 3]
list_b = [4, 5, 6]
print(list_a + list_b)    # [1, 2, 3, 4, 5, 6]  ← 이어붙이기

arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])
print(arr_a + arr_b)      # [5 7 9]  ← 같은 자리끼리 더하기
```

</details>

In [ ]:
# 리스트끼리 "+"을 하면 이어붙이기(연결)가 되어버림 — 전혀 다른 결과!
list_a = [1, 2, 3]
list_b = [4, 5, 6]
print(list_a + list_b)    # [1, 2, 3, 4, 5, 6]

# 같은 자리끼리 더해줌
arr_a = np.array([1,2,3])
arr_b = np.array([4,5,6])
print(arr_a + arr_b)


[1, 2, 3, 4, 5, 6]
[5 7 9]


| 구분 | 파이썬 리스트 | NumPy 배열 |
|---|---|---|
| `*` 연산 | 반복(복제) | 각 요소에 곱셈 |
| `+` 연산 | 이어붙이기(연결) | 같은 위치끼리 덧셈 |
| 전체 값 계산 | 반복문/컴프리헨션 필요 | 연산자를 그대로 적용 가능 |
| 조건으로 골라내기 | 반복문 + if 필요 | `arr[arr > 190]` 한 줄 |
| 속도 (대량 데이터) | 상대적으로 느림 | 훨씬 빠름 |
| 자료형 제약 | 서로 다른 자료형 혼합 가능 | 동일한 자료형만 저장 (그래서 빠름) |

> 💡 **핵심 요약**: 리스트의 `+`, `*`는 "이어붙이기", "반복"이지만, NumPy 배열의 `+`, `*`는 수학적인 "덧셈", "곱셈"입니다. 숫자 데이터를 다룬다면 리스트보다 NumPy 배열이 훨씬 직관적이고 빠릅니다.


## ⚠️ 자주 하는 실수

> ⚠️ 리스트와 NumPy 배열의 `+`/`*` 연산 결과가 다르다는 것을 잊고 혼동하는 경우가 매우 흔합니다.

> ⚠️ 서로 다른 `shape`(모양)의 배열끼리 연산하려다 `ValueError: operands could not be broadcast together`가 나는 경우가 있습니다.

> ⚠️ `arr.shape`는 함수 호출이 아니라 속성이므로 괄호 없이 사용해야 합니다 (`arr.shape()` ❌, `arr.shape` ✅).

> ⚠️ axis=0과 axis=1을 반대로 지정해서 "종목별 평균"을 구하려다 "날짜별 평균"을 구하는 실수 — 결과의 **개수**를 보고 검산하세요 (종목이 3개인데 결과가 5개면 방향이 틀린 것).

> ⚠️ `np.where(조건)`처럼 값 2개를 빼먹으면 인덱스 튜플이 반환됩니다. 값을 바꾸려면 반드시 3개 인자를 채우세요.


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
a = np.array([1, 2, 3])
b = np.array([1, 2])
# print(a + b)   # ❌ ValueError: 모양이 다름 (3개 vs 2개)
print(a.shape, b.shape)   # 연산 전에 shape부터 확인하는 습관!
```

</details>

In [ ]:
# 코드 입력

a = np.array([1, 2, 3])
b = np.array([1, 2])
# print(a + b)   # ❌ ValueError: 모양이 다름 (3개 vs 2개)
print(a.shape, b.shape)   # 연산 전에 shape부터 확인하는 습관!


(3,) (2,)


## 🚀 실무에서는?

> 🚀 NumPy는 이미지 처리(이미지를 숫자 배열로 취급), 딥러닝의 텐서 연산, 대량의 수치 데이터를 빠르게 계산해야 하는 모든 곳에서 사용됩니다. 3주차에 배울 머신러닝(scikit-learn)과 딥러닝의 데이터가 전부 NumPy 배열 형태로 흘러 다닙니다. 오늘 배운 shape 확인, axis, 불리언 인덱싱은 AI 모델링 내내 다시 만나는 기본기입니다.


## 🧩 Check Point

**Q1.** `np.array([1,2,3]) * 2`의 결과는? ① `[1,2,3,1,2,3]` ② `[2,4,6]` ③ 에러 ④ `[1,2,3]`
<details><summary>정답</summary>② `[2, 4, 6]`</details>

**Q2.** 2차원 배열에서 `arr[1, 2]`가 의미하는 것은? ① 1행 전체 ② 2행 3열 값 ③ 1열 전체 ④ 에러
<details><summary>정답</summary>② 2행 3열 값 (인덱스는 0부터 시작하므로 [1,2]는 2번째 행, 3번째 열)</details>

**Q3.** 3개 종목 x 5일치 배열에서 "종목별 평균"을 구하는 코드는? ① `arr.mean()` ② `arr.mean(axis=0)` ③ `arr.mean(axis=1)` ④ `arr.argmax()`
<details><summary>정답</summary>③ `arr.mean(axis=1)` — 행(종목) 방향으로 계산. 결과가 3개(종목 수)인지로 검산!</details>

**Q4.** `prices[prices > 100]`이 하는 일은? ① 100보다 큰 값의 개수 ② 100보다 큰 값만 골라낸 배열 ③ True/False 배열 ④ 에러
<details><summary>정답</summary>② 100보다 큰 값만 골라낸 배열 (③ True/False 배열은 `prices > 100`까지만 했을 때)</details>

**Q5.** "가장 판매량이 많았던 날이 며칠째인지"를 알려주는 함수는? ① `max()` ② `argmax()` ③ `sort()` ④ `where()`
<details><summary>정답</summary>② `argmax()` — max()는 값을, argmax()는 위치를 알려줍니다</details>


## 💻 실습

> 🌙 **자율 멘토링 시간에 진행합니다.** 아래 TODO를 예시 정답을 보지 않고 먼저 풀어보세요. 난이도가 단계적으로 올라갑니다.


In [ ]:
# TODO 1 (배열 생성)
# 테슬라 5일치 종가 [248.5, 251.3, 245.1, 253.8, 260.2]로 배열을 만드세요


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
import numpy as np
tesla = np.array([248.5, 251.3, 245.1, 253.8, 260.2])
print(tesla)
```

</details>

In [1]:
# 코드 입력

import numpy as np
tesla = np.array([248.5, 251.3, 245.1, 253.8, 260.2])
print(tesla)


[248.5 251.3 245.1 253.8 260.2]


In [ ]:
# TODO 2 (통계 함수)
# 위 테슬라 배열의 평균, 최댓값, 최솟값을 구하세요


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print(tesla.mean(), tesla.max(), tesla.min())
```

</details>

In [3]:
# 코드 입력

print(tesla.mean(), tesla.max(), tesla.min())


251.78000000000003 260.2 245.1


In [ ]:
# TODO 3 (인덱싱/슬라이싱)
# 테슬라 배열에서 마지막 3일치만 슬라이싱해서 출력하세요


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print(tesla[-3:])
```

</details>

In [4]:
# 코드 입력

print(tesla[-3:])


[245.1 253.8 260.2]


In [ ]:
# TODO 4 (연산)
# 테슬라 종가에 각각 5% 수수료를 더한 새 배열을 만드세요


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print(tesla * 1.05)
```

</details>

In [5]:
# 코드 입력

new_tesla = tesla * 1.05
print(new_tesla)


[260.925 263.865 257.355 266.49  273.21 ]


In [ ]:
# TODO 5 (argmax)
# 테슬라 배열에서 최고가가 며칠째(몇 번 인덱스)였는지 구하세요


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print(tesla.argmax())   # 4 → 5일째
```

</details>

In [6]:
# 코드 입력

print(tesla.argmax())   # 4번 인덱스: 5일째


4


In [ ]:
# TODO 6 (불리언 인덱싱)
# 테슬라 종가 중 250 이상이었던 날의 값만 골라내고, 며칠이었는지 세어보세요


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print(tesla[tesla >= 250])
print((tesla >= 250).sum(), "일")
```

</details>

In [7]:
# 코드 입력

print(tesla[tesla >= 250])
print((tesla >= 250).sum(), "일")


[251.3 253.8 260.2]
3 일


In [ ]:
# TODO 7 (np.where)
# 테슬라 종가가 250 이상이면 "고가", 아니면 "저가"로 라벨 배열을 만드세요


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print(np.where(tesla >= 250, "고가", "저가"))
```

</details>

In [8]:
# 코드 입력

print(np.where(tesla >= 250, '고가', '저가'))


['저가' '고가' '저가' '고가' '고가']


In [ ]:
# TODO 8 (2차원 + axis)
# 엔비디아·애플 5일치 종가로 2행 5열 배열을 만들고,
# 각 종목의 평균(axis=1)과 각 날짜의 평균(axis=0)을 모두 구하세요


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
stocks = np.array([
    [135.58, 137.71, 140.15, 138.90, 142.30],   # 엔비디아
    [189.51, 191.20, 193.42, 187.80, 195.90]    # 애플
])
print(stocks.mean(axis=1))   # 종목별 평균
print(stocks.mean(axis=0))   # 날짜별 평균
```

</details>

In [9]:
# 코드 입력

stocks = np.array([
    [135.58, 137.71, 140.15, 138.90, 142.30],   # 엔비디아
    [189.51, 191.20, 193.42, 187.80, 195.90]    # 애플
])
print(stocks.mean(axis=1))   # 종목별 평균
print(stocks.mean(axis=0))   # 각 날짜의 평균

[138.928 191.566]
[162.545 164.455 166.785 163.35  169.1  ]


In [ ]:
# TODO 9 (리스트 vs 배열 비교)
# [1,2,3]에 *3을 리스트와 NumPy 배열로 각각 적용해 차이를 확인하세요


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print([1, 2, 3] * 3)
print(np.array([1, 2, 3]) * 3)
```

</details>

In [10]:
# 코드 입력

print([1,2,3]*3)
print(np.array([1,2,3])*3)


[1, 2, 3, 1, 2, 3, 1, 2, 3]
[3 6 9]


## 📝 실습 과제

> 🌙 자율 멘토링 시간에 풀어보는 심화 과제입니다.


In [ ]:
# 과제 1
# 삼성전자 일주일치 종가 [71000, 71500, 70200, 72100, 71800, 73000, 72500]으로 배열을 만들고
# 평균 대비 각 날짜의 차이(편차)를 구하세요

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 과제 1 답안

import numpy as np

# 삼성전자 일주일 종가
prices = np.array([71000, 71500, 70200, 72100, 71800, 73000, 72500])

# 평균
mean_price = prices.mean()

# 평균 대비 편차
deviation = prices - mean_price

print("평균:", mean_price)
print("편차:", deviation)
```

</details>

In [12]:
# 코드 입력

samsung = np.array([71000, 71500, 70200, 72100, 71800, 73000, 72500])

deviation = samsung - samsung.mean()

print("평균:", samsung.mean())
print("편차:", deviation)


평균: 71728.57142857143
편차: [ -728.57142857  -228.57142857 -1528.57142857   371.42857143
    71.42857143  1271.42857143   771.42857143]


In [ ]:
# 과제 2: 엔비디아, 애플, 테슬라 3개 종목의 3일치 종가로 3x3 배열을 만들고
#         각 종목(행)별 최댓값과, 각 날짜(열)별 평균을 각각 구하세요 (axis=1, axis=0 활용)



<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
import numpy as np

# 엔비디아, 애플, 테슬라 (행) / 3일치 종가 (열)
prices = np.array([
    [180, 182, 185],   # 엔비디아
    [210, 208, 215],   # 애플
    [320, 318, 325]    # 테슬라
])

# 각 종목(행)별 최댓값
stock_max = prices.max(axis=1)

# 각 날짜(열)별 평균
day_mean = prices.mean(axis=0)

print("종목별 최고가:", stock_max)
print("날짜별 평균:", day_mean)
```

</details>

In [14]:
# 코드 입력

stocks = np.array([
    [180, 182, 185],
    [210, 208, 215],
    [320, 318, 325]
])

stock_max = stocks.max(axis=1)  # 종목(행)별 최댓값
day_mean = stocks.mean(axis=0)  # 날짜(열)별 평균

print('종목별 최댓값: ', stock_max)
print('날짜별 평균: ', day_mean)


종목별 최댓값:  [185 215 325]
날짜별 평균:  [236.66666667 236.         241.66666667]


In [ ]:
# 과제 3
# 과제 1의 삼성전자 배열에서 "평균보다 높았던 날"의 종가만 골라내고,
# 그런 날이 총 며칠인지 구하세요 (불리언 인덱싱 활용)


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
import numpy as np

prices = np.array([71000, 71500, 70200, 72100, 71800, 73000, 72500])

# 평균
mean_price = prices.mean()

# 평균보다 높은 종가만 선택
high_prices = prices[prices > mean_price]

# 평균보다 높았던 날의 수
high_count = len(high_prices)

print("평균 종가:", mean_price)
print("평균보다 높은 종가:", high_prices)
print("평균보다 높았던 날:", high_count, "일")
```

</details>

In [18]:
# 코드 입력

samsung = np.array([71000, 71500, 70200, 72100, 71800, 73000, 72500])

# 평균
mean_price = samsung.mean()

# 평균보다 높았던 날 종가
high_prices = samsung[samsung > mean_price]

high_count = len(high_prices)

print('평균: ', mean_price)
print('평균보다 높았던 날 종가:', high_prices)
print('평균보다 높았던 날 수:', high_count, "일")


평균:  71728.57142857143
평균보다 높았던 날 종가: [72100 71800 73000 72500]
평균보다 높았던 날 수: 4 일


In [ ]:
# 과제 4
# 카페 일주일 판매량 [120, 135, 98, 150, 210, 260, 240] (월~일)에 대해
# (1) 가장 많이 팔린 요일의 "요일 이름"을 출력하고 (argmax + 요일 리스트 활용)
# (2) 150잔 이상이면 "성수", 미만이면 "비수"인 라벨 배열을 만드세요 (np.where)


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 과제 4 답안

import numpy as np

# 일주일 판매량
sales = np.array([120, 135, 98, 150, 210, 260, 240])

# 요일
days = ["월", "화", "수", "목", "금", "토", "일"]

# (1) 가장 많이 팔린 요일
best_day = days[sales.argmax()]

# (2) 성수 / 비수 라벨
labels = np.where(sales >= 150, "성수", "비수")

print("가장 많이 팔린 요일:", best_day)
print("성수/비수:", labels)
```

</details>

In [20]:
# 코드 입력

sales = np.array([120, 135, 98, 150, 210, 260, 240])
days = ['월', '화', '수', '목', '금', '토', '일']

best_day = days[sales.argmax()]
labels = np.where(sales >= 150, '성수', '비수')

print('가장 많이 팔린 요일:', best_day)
print('성수/비수:', labels)


가장 많이 팔린 요일: 토
성수/비수: ['비수' '비수' '비수' '성수' '성수' '성수' '성수']


## 📌 핵심 정리

- `np.array()`로 배열 생성, `shape`/`ndim`/`dtype`/`size`로 속성 확인 — 배열은 **동일 자료형**만 저장
- 인덱싱/슬라이싱: 1차원은 `arr[i]`, 2차원은 `arr[행, 열]` (`:`는 "전부")
- 배열의 `+`, `*`는 리스트와 달리 실제 수학 연산 (같은 위치끼리 계산) — 환율, 할인, 수익률이 한 줄로
- 통계: `mean()`/`sum()`/`max()`/`min()`/`std()` + 위치를 찾는 `argmax()`/`argmin()`
- **axis=0은 ↓열별, axis=1은 →행별** — 결과 개수로 검산하는 습관
- 불리언 인덱싱 `arr[arr > 값]` = 조건으로 골라내기 — 다음 시간 Pandas 필터링의 원리
- `np.where(조건, 참값, 거짓값)` = 조건에 따라 값 바꾸기
- `np.sort()` 정렬, `reshape()` 모양 변경 (요소 개수 유지)


## 🌙 더 깊이 알아보기

> 💤 아래 내용은 정규 수업 시간에는 다루지 않는 참고/자율학습용 자료입니다.

### `dtype` 명시적으로 지정하기


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
arr = np.array([1, 2, 3], dtype=np.float64)
print(arr)        # [1. 2. 3.]
print(arr.dtype)  # float64
```

</details>

In [21]:
# 코드 입력

arr = np.array([1, 2, 3], dtype=np.float64)
print(arr)        # [1. 2. 3.]
print(arr.dtype)  # float64


[1. 2. 3.]
float64


### 난수 배열 생성 — 실험용 가짜 데이터 만들기


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
np.random.seed(42)   # 재현 가능한 결과를 위한 시드 고정
random_prices = np.random.uniform(100, 200, 5)   # 100~200 사이 무작위 실수 5개
print(random_prices)

random_int = np.random.randint(1, 7, 10)         # 주사위 10번 굴리기
print(random_int)
```

</details>

In [22]:
# 코드 입력

np.random.seed(42)   # 재현 가능한 결과를 위한 시드 고정
random_prices = np.random.uniform(100, 200, 5)   # 100~200 사이 무작위 실수 5개
print(random_prices)

random_int = np.random.randint(1, 7, 10)         # 주사위 10번 굴리기
print(random_int)


[137.45401188 195.07143064 173.19939418 159.86584842 115.60186404]
[3 3 3 5 4 3 6 5 2 4]


### 여러 조건 결합하기 — `&`(그리고), `|`(또는)

조건이 2개 이상이면 각 조건을 **괄호로 감싸고** `&`, `|`로 연결합니다. (다음 시간 Pandas 다중 조건 필터링에서 본격적으로 다룹니다)


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
prices = np.array([189.5, 191.2, 187.8, 193.4, 195.9])
print(prices[(prices > 188) & (prices < 194)])   # 188 초과 그리고 194 미만
```

</details>

In [ ]:
# 코드 입력

prices = np.array([189.5, 191.2, 187.8, 193.4, 195.9])
print(prices[(prices > 188) & (prices < 194)])   # 188 초과 그리고 194 미만


# 📘 CH06-03. Pandas (Series, DataFrame)

## 🤔 먼저 생각해보기

> **엑셀 스프레드시트처럼, 종목명·현재가·등락률이 함께 있는 표를 파이썬으로 다루려면 어떻게 해야 할까요?**

NumPy 배열은 숫자 계산에는 강력하지만, 종목명 같은 문자열과 가격 같은 숫자가 함께 있는 "표"를 다루기엔 불편합니다.
엑셀 같은 표 형태의 데이터를 다루기 위한 도구가 **Pandas**입니다. 오늘 수업이 끝나면 이런 질문에 답할 수 있게 됩니다.

- 종목명으로 바로 가격을 조회하려면?
- 표에 "평가금액" 컬럼을 계산해서 붙이려면?
- 매출액이 가장 큰 메뉴를 찾고, 표를 매출 순으로 줄 세우려면?


## 📖 핵심 개념

### 1) Pandas란?

- Pandas의 핵심 자료구조는 두 가지입니다.
  - **Series**: 1차원 데이터 (인덱스가 붙은 하나의 열)
  - **DataFrame**: 2차원 데이터 (여러 개의 Series가 모인 표 전체)
- Pandas는 NumPy 위에 만들어졌습니다. **"NumPy 배열 + 이름표(인덱스/컬럼명)"** 라고 이해하면 정확합니다. 방금 배운 배열 연산·불리언 인덱싱 원리가 여기서 그대로 재사용됩니다.


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
import pandas as pd   # 관례적으로 pd라는 별칭을 사용
import numpy as np
```

</details>

In [ ]:
# 코드 입력


import pandas as pd
import numpy as np


### 2) Series — 1차원 데이터

Series는 "값 + 인덱스"의 쌍입니다. NumPy 배열과의 차이는 **각 값에 이름표를 붙일 수 있다**는 것입니다.


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
prices = pd.Series([135.58, 189.51, 248.50])
print(prices)
# 0    135.58
# 1    189.51
# 2    248.50
# dtype: float64
# ← 왼쪽의 0,1,2가 "인덱스" (지정하지 않으면 자동으로 번호가 붙음)
```

</details>

In [ ]:
# 코드 입력

prices = pd.Series([135.58, 189.51, 248.50])
print(type(prices))
print(prices)
prices  # 그냥 이렇게 쓰는 게 깔끔하게 표로 나옴

<class 'pandas.core.series.Series'>
0    135.58
1    189.51
2    248.50
dtype: float64


,0
0,135.58
1,189.51
2,248.50


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 인덱스를 직접 지정하기 — 이름표를 붙이는 순간 조회가 편해짐
prices = pd.Series([135.58, 189.51, 248.50], index=["엔비디아", "애플", "테슬라"])
print(prices)

print(prices["애플"])    # 189.51  ← 이름으로 조회 가능
print(prices[["엔비디아", "테슬라"]])   # 여러 개를 한 번에 (대괄호 두 번)
```

</details>

In [ ]:
# 인덱스를 직접 지정하기 — 이름표를 붙이는 순간 조회가 편해짐

prices = pd.Series([135.58, 189.51, 248.50], index=['엔비디아', '애플', '테슬라'])
prices

# 인덱스 (이름)으로 지정
print(prices['애플'])

# 여러 개를 한 번에
print(prices[['엔비디아', '테슬라']])

189.51
엔비디아    135.58
테슬라     248.50
dtype: float64


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 2: 커피 메뉴 가격표 — 같은 원리, 다른 데이터
menu = pd.Series([4500, 5000, 5500], index=["아메리카노", "라떼", "콜드브루"])
print(menu)
print(menu["라떼"])
```

</details>

In [ ]:
# 예시 2: 커피 메뉴 가격표 — 같은 원리, 다른 데이터





<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 3: 반 학생들의 시험 점수
score = pd.Series([90, 65, 72, 88], index=["김민준", "이서연", "박지훈", "최수아"])
print(score)
print(score["최수아"])
```

</details>

In [ ]:
# 예시 3: 반 학생들의 시험 점수





<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 인덱스에 특정 이름이 있는지 확인 — in 연산자
print("애플" in prices)      # True
print("삼성전자" in prices)   # False
```

</details>

In [ ]:
# 인덱스에 특정 이름이 있는지 확인 — in 연산자





### 3) Series 연산 — NumPy에서 배운 그대로!

Series에도 배열 연산이 그대로 적용됩니다. 게다가 통계 메서드도 똑같이 씁니다.


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
menu = pd.Series([4500, 5000, 5500], index=["아메리카노", "라떼", "콜드브루"])

# 예시 1: 전 메뉴 10% 인상 — NumPy 브로드캐스팅과 동일
print(menu * 1.1)
```

</details>

In [ ]:
# 코드 입력





<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 2: 통계 메서드 — mean, max, min, sum 전부 그대로
score = pd.Series([90, 65, 72, 88], index=["김민준", "이서연", "박지훈", "최수아"])
print(score.mean())   # 평균
print(score.max())    # 최고점
print(score.sum())    # 총점
```

</details>

In [ ]:
# 예시 2: 통계 메서드 — mean, max, min, sum 전부 그대로





<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 3: 조건으로 골라내기 — NumPy 불리언 인덱싱과 완전히 동일한 원리
print(score[score >= 80])   # 80점 이상 학생만 (이름표가 함께 따라옴!)
```

</details>

In [ ]:
# 예시 3: 조건으로 골라내기 — NumPy 불리언 인덱싱과 완전히 동일한 원리





<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# Series끼리 연산하면 "인덱스가 같은 것끼리" 자동으로 계산됨
mid_term = pd.Series([90, 65, 72], index=["김민준", "이서연", "박지훈"])
final    = pd.Series([85, 95, 60], index=["김민준", "이서연", "박지훈"])

total = mid_term + final
print(total)   # 학생별 중간+기말 합산이 이름 기준으로 자동 매칭
```

</details>

In [ ]:
# Series끼리 연산하면 "인덱스가 같은 것끼리" 자동으로 계산됨

mid_term = pd.Series([90, 65, 72], index=["김민준", "이서연", "박지훈"])
final    = pd.Series([85, 95, 60], index=["김민준", "이서연", "박지훈"])





> 💡 NumPy 배열은 "같은 위치끼리", Series는 **"같은 인덱스(이름)끼리"** 계산합니다. 위치가 아니라 이름으로 맞춰준다는 것이 Pandas의 진화 포인트입니다.

### 4) DataFrame 생성하기

DataFrame은 여러 Series가 옆으로 모인 "표"입니다. 만드는 방법을 3가지 익혀둡시다.


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 방법 A: 딕셔너리로 생성 (컬럼이름: 값 목록) — 가장 많이 쓰는 방법

data = {
    "메뉴": ["엽기떡볶이", "교촌 허니콤보", "맥도날드 상하이"],
    "카테고리": ["분식", "치킨", "패스트푸드"],
    "배달비": [3000, 4000, 2500],
    "만족도(%)": [95.2, 91.8, 89.5]
}

df = pd.DataFrame(data)

df   # 노트북에서는 print 없이 마지막 줄에 두면 표가 예쁘게 렌더링됩니다
```

</details>

In [ ]:
# 방법 A: 딕셔너리로 생성 (컬럼이름: 값 목록) — 가장 많이 쓰는 방법





<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 방법 B: 리스트의 리스트 + 컬럼명 지정 — 행 단위로 데이터가 있을 때

rows = [
    ["아이스 아메리카노", "에스프레소", 4500, "Tall"],
    ["자바칩 프라푸치노", "블렌디드", 6300, "Grande"],
    ["자몽 허니 블랙티", "티바나", 5700, "Tall"]
]

df = pd.DataFrame(rows, columns=["메뉴명", "카테고리", "가격", "추천사이즈"])

df
```

</details>

In [ ]:
# 방법 B: 리스트의 리스트 + 컬럼명 지정 — 행 단위로 데이터가 있을 때





<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 방법 C: 딕셔너리의 리스트 — 한 행이 딕셔너리 하나 (웹/API 데이터가 흔히 이 모양)

records = [
    {"콘텐츠명": "호프", "장르": "SF", "공개연도": 2026},
    {"콘텐츠명": "미니언즈", "장르": "애니메이션", "공개연도": 2026},
    {"콘텐츠명": "모아나", "장르": "모험", "공개연도": 2026}
]

df = pd.DataFrame(records)

df

```

</details>

In [ ]:
# 방법 C: 딕셔너리의 리스트 — 한 행이 딕셔너리 하나 (웹/API 데이터가 흔히 이 모양)





In [ ]:
# 참고: 학생 성적표





> ⚠️ 딕셔너리로 만들 때 **각 리스트의 길이가 다르면 에러**가 발생합니다. (3명 이름에 점수 2개를 넣을 수는 없으니까요)

### 5) 컬럼(열) 선택하기

대괄호 개수가 결과의 자료형을 결정합니다. **한 번이면 Series, 두 번이면 DataFrame** — 오늘 가장 많이 반복할 문장입니다.


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 코드 입력

cafe = pd.DataFrame({
    "메뉴": ["아메리카노", "카페라떼", "딸기스무디"],
    "가격": [4500, 5000, 6000],
    "칼로리": [10, 180, 320],
    "인기순위": [1, 2, 3]
})

# 하나의 컬럼 → Series로 반환
print(cafe["메뉴"])
print(type(cafe["메뉴"]))

```

</details>

In [ ]:
# 코드 입력





<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 코드 입력
# 여러 컬럼 → DataFrame으로 반환 (대괄호 두 번!)

cafe[["메뉴", "칼로리"]]

```

</details>

In [ ]:
# 여러 컬럼 → DataFrame으로 반환 (대괄호 두 번!)






<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 2: 성적표에서 — 이름과 수학만 뽑은 "부분 표" 만들기
students[["이름", "수학"]]
```

</details>

In [ ]:
# 예시 2: 성적표에서 — 이름과 수학만 뽑은 "부분 표" 만들기






<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 3: 뽑은 컬럼(Series)에 바로 연산·통계 적용

# 전 메뉴 10% 인상하기
print(cafe["가격"] * 1.1)      

# 수학 평균
print(students["수학"].mean())

```

</details>

In [ ]:
# 예시 3: 뽑은 컬럼(Series)에 바로 연산·통계 적용

# 전 메뉴 10% 인상하기




# 수학 평균






### 6) 행 선택하기 — `loc`와 `iloc` 살짝 맛보기 (자세한 내용은 CH07에서)


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 코드 입력

# 인덱스 이름(라벨)으로 0번 행 선택
print(cafe.loc[0])    

# 순서(위치)로 0번째 행 선택 — 지금은 결과가 같음
print(cafe.iloc[0])

```

</details>

In [ ]:
# 코드 입력

# 인덱스 이름(라벨)으로 0번 행 선택



# 순서(위치)로 0번째 행 선택 — 지금은 결과가 같음





<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 조건으로 행 선택 (불리언 인덱싱)
# NumPy에서 배운 원리가 표에서도 그대로!


df[cafe["가격"] >= 6000]

```

</details>

In [ ]:
# 조건으로 행 선택 (불리언 인덱싱)
# NumPy에서 배운 원리가 표에서도 그대로!





<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 칼로리가 100 이상인것만

cafe[cafe["칼로리"] > 100]

```

</details>

In [ ]:
# 칼로리가 100 이상인것만





> 💡 `cafe[cafe["칼로리"] > 100]`의 안쪽 `cafe["칼로리"] > 100`은 True/False Series입니다. NumPy의 `arr[arr > 100]`과 완전히 같은 2단계 원리이지요. 다중 조건, isin 등 본격적인 필터링은 **다음 시간(CH07)** 에 배웁니다.

### 7) 컬럼 추가/삭제/계산

실무 데이터 분석의 절반은 "기존 컬럼으로 새 컬럼 만들기"입니다. 여러 상황으로 손에 익혀봅시다.


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 1. 새로운 컬럼 '주문수량' 추가 (오늘 각 메뉴가 몇 잔 팔렸는지)
cafe["주문수량"] = [25, 18, 12]

cafe
```

</details>

In [ ]:
# 1. 새로운 컬럼 '주문수량' 추가 (오늘 각 메뉴가 몇 잔 팔렸는지)




<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
cafe["총매출액"] = cafe["가격"] * cafe["주문수량"]

cafe
```

</details>

In [ ]:
# 2. 기존의 '가격'과 새로 만든 '주문수량'을 곱해서 '총매출액' 계산




<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
cafe = cafe.drop("인기순위", axis=1)   # axis=1: 열 기준 삭제
cafe
```

</details>

In [ ]:
# 컬럼 삭제




<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 3: 성적표 — 총점과 평균 컬럼 만들기
students["총점"] = students["국어"] + students["영어"] + students["수학"]
students["평균"] = (students["총점"] / 3).round(1)
students
```

</details>

In [ ]:
# 성적표 — 총점과 평균 컬럼 만들기




<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 모든 행에 같은 값 넣기
cafe["카테고리"] = "음료"

# 조건에 따라 다른 값 넣기 (np.where 재사용!)
# NumPy 함수가 Series에도 그대로

cafe["인기도"] = np.where(cafe["주문수량"] >= 15, "인기", "일반")
cafe

```

</details>

In [ ]:
# 모든 행에 같은 값 넣기




# 조건에 따라 다른 값 넣기 (np.where 재사용!)
# NumPy 함수가 Series에도 그대로




> 💡 `df["새컬럼"] = ...` — 없는 이름에 대입하면 **추가**, 있는 이름에 대입하면 **덮어쓰기**입니다.

### 8) 컬럼 통계 메서드 — 표에게 질문하기

컬럼(Series)에 통계 메서드를 부르면 표가 대답합니다. "값"을 묻는 함수와 "누가/무엇이"를 묻는 함수를 짝으로 기억하세요. (표 전체 요약(describe 등)은 다음 시간 CH07에서 배웁니다)


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# "값"을 묻는 질문들

print("매출 평균:", cafe["총매출액"].mean())
print("매출 총합:", cafe["총매출액"].sum())
print("최고 매출:", cafe["총매출액"].max())

```

</details>

In [ ]:
# "값"을 묻는 질문들





<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# "무엇이?"를 묻는 질문
# idxmax / idxmin (NumPy의 argmax와 같은 역할)

best = cafe["총매출액"].idxmax() # 최고 매출인 "행의 인덱스"

print(best)
print('=' * 50)

# 그 행 전체를 확인
print(cafe.loc[best])

print('=' * 50)
# 그 행의 메뉴 이름만 콕 집어서
print(cafe.loc[best, "메뉴"])  

```

</details>

In [ ]:
# "무엇이?"를 묻는 질문
# idxmax / idxmin (NumPy의 argmax와 같은 역할)




<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 2: 성적표 — 수학을 가장 잘 본 학생은?
top = students["수학"].idxmax()
print(students.loc[top, "이름"], students.loc[top, "수학"], "점")
```

</details>

In [ ]:
# 예시 2: 성적표 — 수학을 가장 잘 본 학생은?





### 9) 정렬 — `sort_values()`

"줄 세우기"는 분석의 기본 동작입니다. 어떤 컬럼 기준으로, 어느 방향으로 세울지만 정하면 됩니다.


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 기본: 오름차순 (작은 값부터)
cafe.sort_values("총매출액")
```

</details>

In [ ]:
# 기본: 오름차순 (작은 값부터)




<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 내림차순: ascending=False (큰 값부터) — "매출 순위표"가 한 줄에
cafe.sort_values("총매출액", ascending=False)
```

</details>

In [ ]:
# 내림차순: ascending=False (큰 값부터) — "매출 순위표"가 한 줄에





<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 2: 성적표를 평균 순으로
students.sort_values("평균", ascending=False)
```

</details>

In [ ]:
# 예시 2: 성적표를 평균 순으로




<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 여러 기준으로 정렬 — 리스트로 전달 (앞 기준이 같을 때 뒤 기준 적용)
students.sort_values(["수학", "영어"], ascending=False)
```

</details>

In [ ]:
# 여러 기준으로 정렬 — 리스트로 전달 (앞 기준이 같을 때 뒤 기준 적용)






> ⚠️ `sort_values()`는 정렬된 **새 표를 반환**할 뿐, 원본 `cafe`는 그대로입니다. 정렬 결과를 계속 쓰려면 `cafe_sorted = cafe.sort_values(...)`처럼 변수에 담으세요.

### 10) 서로 다른 자료형 비교 — Series vs DataFrame


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
s = pd.Series([135.58, 189.51, 248.50])   # 1차원
print(type(s))       # <class 'pandas.core.series.Series'>

df2 = pd.DataFrame({"현재가": [135.58, 189.51, 248.50]})   # 2차원 (컬럼이 1개뿐이어도 DataFrame)
print(type(df2))     # <class 'pandas.core.frame.DataFrame'>

# DataFrame에서 컬럼 하나를 뽑으면 다시 Series가 됨
print(type(df2["현재가"]))   # <class 'pandas.core.series.Series'>
```

</details>

In [ ]:
# 코드 입력





| 구분 | Series | DataFrame |
|---|---|---|
| 차원 | 1차원 (하나의 열) | 2차원 (여러 열이 모인 표) |
| 비유 | 엑셀의 한 개 열 | 엑셀 시트 전체 |
| 생성 방법 | `pd.Series([...])` | `pd.DataFrame({...})` |
| DataFrame과의 관계 | DataFrame의 각 컬럼이 Series | 여러 Series가 모여서 구성됨 |

> 💡 **핵심 요약**: DataFrame에서 컬럼을 하나만 뽑으면 Series가 되고, 여러 Series를 옆으로 나란히 붙이면 DataFrame이 됩니다. 그리고 NumPy에서 배운 연산·통계·조건 선택의 원리가 Series에서 "이름표가 붙은 채로" 그대로 동작합니다.

**오늘의 3층 구조로 정리하면:**

```
NumPy 배열   : 값                     (위치로만 접근)
Series       : 값 + 인덱스             (이름으로 접근 가능)
DataFrame    : 여러 Series + 컬럼명    (표 전체)
```


## ⚠️ 자주 하는 실수

> ⚠️ 컬럼을 하나만 선택할 때 `df["종목"]`(대괄호 1번)과 `df[["종목"]]`(대괄호 2번)을 헷갈리는 경우가 흔합니다 — 전자는 Series, 후자는 DataFrame이 반환됩니다.

> ⚠️ `df.drop("컬럼명")`에서 `axis=1`을 빼먹어서 행을 삭제하려 한 것으로 오인되어 에러가 나는 경우가 있습니다 (기본값은 axis=0, 즉 행 삭제).

> ⚠️ 딕셔너리로 DataFrame을 만들 때 각 리스트의 길이가 다르면 에러가 발생합니다.

> ⚠️ `sort_values()`, `drop()`의 결과를 변수에 담지 않고 "왜 안 바뀌지?"라고 헤매는 경우 — 대부분의 Pandas 메서드는 **원본을 두고 새 결과를 반환**합니다.
> ⚠️ 존재하지 않는 컬럼명을 조회하면 `KeyError`가 납니다 — 오타(공백 포함)가 대부분의 원인이니 `df.columns`로 정확한 이름을 확인하세요.


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
print(type(df["종목"]))     # <class '...Series'>
print(type(df[["종목"]]))   # <class '...DataFrame'>

# df.drop("현재가")          # ❌ 기본은 행(index) 삭제 시도라 에러
df.drop("현재가", axis=1)    # ✅ 컬럼 삭제는 axis=1 명시
```

</details>

In [ ]:
# 코드 입력

print(type(cafe["메뉴"]))     # <class '...Series'>
print(type(cafe[["메뉴"]]))   # <class '...DataFrame'>

# cafe.drop("칼로리")          # ❌ 기본은 행(index) 삭제 시도라 에러
cafe.drop("칼로리", axis=1)    # ✅ 컬럼 삭제는 axis=1 명시


## 🚀 실무에서는?

> 🚀 실무에서 다루는 데이터의 대부분은 엑셀/CSV/데이터베이스에서 가져온 표 형태이며, Pandas DataFrame은 이런 데이터를 다루는 사실상의 표준 도구입니다. 주가, 매출, 설문 응답 등 거의 모든 정형 데이터 분석이 DataFrame으로 시작됩니다. 오늘 배운 "컬럼 계산 → 통계 질문 → 정렬"의 3단 콤보는 어떤 데이터를 만나도 가장 먼저 하게 되는 기본 동작입니다.


## 🧩 Check Point

**Q1.** `df["가격"]`과 `df[["가격"]]`의 반환 타입 차이는? ① 둘 다 Series ② 둘 다 DataFrame ③ 전자는 Series, 후자는 DataFrame ④ 전자는 DataFrame, 후자는 Series
<details><summary>정답</summary>③ 전자는 Series, 후자는 DataFrame</details>

**Q2.** 컬럼을 삭제할 때 필요한 옵션은? ① `axis=0` ② `axis=1` ③ `column=True` ④ 옵션 불필요
<details><summary>정답</summary>② `axis=1`</details>

**Q3.** "매출액이 가장 큰 행의 인덱스"를 알려주는 메서드는? ① `max()` ② `idxmax()` ③ `sort_values()` ④ `argmax()`
<details><summary>정답</summary>② `idxmax()` — max()는 값만 알려줍니다 (NumPy의 argmax와 같은 역할)</details>

**Q4.** `cafe.sort_values("매출액", ascending=False)`를 실행한 뒤 `cafe`를 출력하면? ① 내림차순 정렬된 표 ② 오름차순 정렬된 표 ③ 원래 순서 그대로 ④ 에러
<details><summary>정답</summary>③ 원래 순서 그대로 — sort_values는 새 표를 반환할 뿐 원본을 바꾸지 않습니다</details>

**Q5.** 중간고사 Series와 기말고사 Series를 더하면 어떤 기준으로 계산될까요? ① 위치 순서끼리 ② 같은 인덱스(이름)끼리 ③ 무작위 ④ 에러
<details><summary>정답</summary>② 같은 인덱스끼리 — 이것이 NumPy 배열과 Series의 결정적 차이입니다</details>


## 💻 실습

> 🌙 **자율 멘토링 시간에 진행합니다.** 아래 TODO를 예시 정답을 보지 않고 먼저 풀어보세요. 난이도가 단계적으로 올라갑니다.


In [ ]:
# TODO 1 (Series)
# 커피 메뉴 3개 ["아메리카노","라떼","콜드브루"]와
# 가격 [4500, 5000, 5500]으로 Series를 만들어 메뉴명을 인덱스로 지정하세요


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
import pandas as pd
menu = pd.Series([4500, 5000, 5500], index=["아메리카노", "라떼", "콜드브루"])
print(menu)
```

</details>

In [ ]:
# 코드 입력





In [ ]:
# TODO 2 (Series 조회/연산)
# 위 menu에서 "라떼"의 가격을 조회하고,
# 전 메뉴 5% 인상가를 출력하세요


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print(menu["라떼"])
print(menu * 1.05)
```

</details>

In [ ]:
# 코드 입력





In [ ]:
# TODO 3 (DataFrame 생성)
# 종목명, 티커, 현재가로 구성된 DataFrame을 딕셔너리로 만드세요
# (엔비디아/NVDA/135.58, 애플/AAPL/189.51, 테슬라/TSLA/248.50)


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
data = {
    "종목": ["엔비디아", "애플", "테슬라"],
    "티커": ["NVDA", "AAPL", "TSLA"],
    "현재가": [135.58, 189.51, 248.50]
}
df = pd.DataFrame(data)
print(df)
```

</details>

In [ ]:
# 코드 입력





In [ ]:
# TODO 4 (컬럼 선택)
# 위 DataFrame에서 "현재가" 컬럼만 Series로, "종목"과 "현재가"를 DataFrame으로 각각 뽑으세요


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print(df["현재가"])
print(df[["종목", "현재가"]])
```

</details>

In [ ]:
# 코드 입력





In [ ]:
# TODO 5 (컬럼 추가+계산)
# "보유수량" 컬럼([10, 5, 8])을 추가하고,
# 현재가 x 보유수량으로 "평가금액" 컬럼을 새로 만드세요


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
df["보유수량"] = [10, 5, 8]
df["평가금액"] = df["현재가"] * df["보유수량"]
print(df)
```

</details>

In [ ]:
# 코드 입력





In [ ]:
# TODO 6 (조건 선택)
# 현재가가 150 이상인 종목만 선택해서 출력하세요


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print(df[df["현재가"] >= 150])
```

</details>

In [ ]:
# 코드 입력





In [ ]:
# TODO 7 (통계+idxmax)
# 평가금액의 평균을 구하고, 평가금액이 가장 큰 종목의 "종목명"을 출력하세요


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print(df["평가금액"].mean())
best = df["평가금액"].idxmax()
print(df.loc[best, "종목"])
```

</details>

In [ ]:
# 코드 입력





In [ ]:
# TODO 8 (정렬)
# DataFrame을 평가금액 내림차순으로 정렬해서 출력하세요 (원본은 유지)


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 예시 정답
print(df.sort_values("평가금액", ascending=False))
```

</details>

In [ ]:
# 코드 입력





## 📝 실습 과제

> 🌙 자율 멘토링 시간에 풀어보는 심화 과제입니다.


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 과제 1: 학생 3명(이름, 국어, 영어, 수학 점수)으로 DataFrame을 만들고
#         "총점"과 "평균" 컬럼을 각각 계산해서 추가하세요

# 과제 2: 커피 메뉴 DataFrame(메뉴명, 가격, 판매량)을 만들고
#         "매출액" = 가격 x 판매량 컬럼을 추가한 뒤,
#         (1) 매출액이 가장 큰 메뉴의 이름을 idxmax()로 찾고
#         (2) 표를 매출액 내림차순으로 정렬하세요

# 과제 3: 과제 1의 성적표에서
#         (1) 평균이 80점 이상인 학생만 조건 선택으로 출력하고
#         (2) np.where를 이용해 평균 80 이상이면 "우수", 미만이면 "노력"인 "등급" 컬럼을 추가하세요
```

</details>

In [ ]:
# 과제 1
# 해외 여행지 3곳의 항공권과 숙박비를 이용해 DataFrame을 만든 뒤,
# "예상경비" 컬럼(항공권 + 숙박비)을 추가하세요.
# 여행지, 항공권, 숙박지 자유롭게 작성


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 과제 1 답안

import pandas as pd

data = {
    "여행지": ["오사카", "세부", "타이페이"],
    "항공권": [280000, 380000, 320000],
    "숙박비": [350000, 300000, 330000]
}

df = pd.DataFrame(data)

# 예상경비 컬럼 추가
df["예상경비"] = df["항공권"] + df["숙박비"]

print(df)
```

</details>

In [ ]:
# 코드 입력





In [ ]:
# 과제 2
# 배달 음식 DataFrame(음식명, 가격, 주문수량)을 만들고
# "결제금액" = 가격 × 주문수량 컬럼을 추가한 뒤,
# (1) 결제금액이 가장 큰 음식의 이름을 idxmax()로 찾고
# (2) 표를 결제금액 내림차순으로 정렬하세요
# 음식명, 가격, 주문수량 자유롭게 작성

<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# 과제 2 답안

import pandas as pd

data = {
    "음식명": ["치킨", "피자", "떡볶이"],
    "가격": [23000, 28000, 14000],
    "주문수량": [2, 1, 3]
}

df = pd.DataFrame(data)

# 결제금액 컬럼 추가
df["결제금액"] = df["가격"] * df["주문수량"]

# (1) 결제금액이 가장 큰 음식
best_food = df.loc[df["결제금액"].idxmax(), "음식명"]
print(best_food)

# (2) 결제금액 내림차순 정렬
df = df.sort_values(by="결제금액", ascending=False)

print(df)
```

</details>

In [ ]:
# 코드 입력





In [ ]:
# 과제 3
# 과제 1의 해외 여행지 데이터에서
# (1) 예상경비가 650,000원 이상인 여행지만 조건 선택으로 출력하고
# (2) np.where를 이용해 예상경비가 650,000원 이상이면 "고비용",
# 미만이면 "가성비"인 "여행유형" 컬럼을 추가하세요.
# 기준 금액은 자유롭게 작성


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
import pandas as pd
import numpy as np

data = {
    "여행지": ["오사카", "세부", "타이페이"],
    "항공권": [280000, 380000, 320000],
    "숙박비": [350000, 300000, 330000]
}

df = pd.DataFrame(data)

# 예상경비 컬럼 추가
df["예상경비"] = df["항공권"] + df["숙박비"]

# (1) 예상경비가 650,000원 이상인 여행지
print(df[df["예상경비"] >= 650000])

# (2) 여행유형 컬럼 추가
df["여행유형"] = np.where(df["예상경비"] >= 650000, "고비용", "가성비")

print(df)
```

</details>

In [ ]:
# 코드 입력





## 📌 핵심 정리

- Series는 1차원(인덱스+값), DataFrame은 2차원(여러 Series의 표) — Pandas = NumPy + 이름표
- Series 연산은 NumPy와 동일하되, Series끼리는 **같은 인덱스끼리** 계산
- DataFrame 생성: 딕셔너리(`{컬럼명: 값목록}`) / 리스트+`columns` / 딕셔너리의 리스트
- 컬럼 선택: `df["컬럼"]`(Series) vs `df[["컬럼"]]`(DataFrame)
- 컬럼 추가: `df["새컬럼"] = 값 또는 계산식` / 삭제: `df.drop("컬럼", axis=1)`
- 컬럼 통계: `mean()/sum()/max()` + 위치를 찾는 `idxmax()` (→ `df.loc[...]`로 행 확인)
- 정렬: `sort_values("컬럼", ascending=False)` — 원본은 그대로, 결과는 변수에 담기
- 조건 선택 맛보기: `df[df["컬럼"] >= 값]` — 본격 필터링은 다음 시간(CH07)에!


## 🌙 더 깊이 알아보기

> 💤 아래 내용은 정규 수업 시간에는 다루지 않는 참고/자율학습용 자료입니다.

### 인덱스를 특정 컬럼으로 지정하기 (CH07에서 다시 만납니다)


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
df_indexed = df.set_index("종목")
print(df_indexed)
print(df_indexed.loc["애플"])   # 이제 종목명으로 바로 조회 가능
```

</details>

In [ ]:
# 코드 입력

df_indexed = df.set_index("종목")
print(df_indexed)
print(df_indexed.loc["애플"])   # 이제 종목명으로 바로 조회 가능


### `to_csv()` / `read_csv()` 살짝 예고


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# df.to_csv("stocks.csv", index=False)   # DataFrame을 CSV로 저장
# df2 = pd.read_csv("stocks.csv")          # CSV를 다시 DataFrame으로 불러오기
```

</details>

In [ ]:
# 코드 입력

# df.to_csv("stocks.csv", index=False)   # DataFrame을 CSV로 저장
# df2 = pd.read_csv("stocks.csv")          # CSV를 다시 DataFrame으로 불러오기


# 🎯 종합 예제 — 오늘 배운 것만으로 미니 포트폴리오 분석

━━━━━━━━━━━━━━━━

> 정규 수업의 마무리입니다. **오늘 배운 NumPy + Pandas 문법만으로** 작은 분석을 처음부터 끝까지 완성해봅니다.
> 새로운 문법은 하나도 등장하지 않습니다 — 전부 오늘 쓴 코드의 재조합입니다.

**시나리오**: 4개 종목을 보유한 나의 포트폴리오. 오늘 배운 도구로 다음 질문에 답해봅시다.

1. 각 종목의 평가금액과 수익금은 얼마인가?
2. 수익 중인 종목만 골라내면?
3. 평가금액이 가장 큰 종목은 무엇인가?
4. 포트폴리오를 수익률 순으로 줄 세우면?


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
import pandas as pd
import numpy as np

# STEP 1. 표 만들기 (DataFrame 생성 — 딕셔너리 방식)
port = pd.DataFrame({
    "종목":   ["엔비디아", "애플", "테슬라", "삼성전자"],
    "매수가": [120.00, 195.00, 240.00, 75000],
    "현재가": [135.58, 189.51, 248.50, 71800],
    "수량":   [10, 5, 8, 20]
})
port
```

</details>

In [ ]:
# 코드 입력

import pandas as pd
import numpy as np

# STEP 1. 표 만들기 (DataFrame 생성 — 딕셔너리 방식)
port = pd.DataFrame({
    "종목":   ["엔비디아", "애플", "테슬라", "삼성전자"],
    "매수가": [120.00, 195.00, 240.00, 75000],
    "현재가": [135.58, 189.51, 248.50, 71800],
    "수량":   [10, 5, 8, 20]
})
port


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# STEP 2. 컬럼 계산 — 평가금액, 수익금, 수익률(%)
port["평가금액"] = port["현재가"] * port["수량"]
port["수익금"]  = (port["현재가"] - port["매수가"]) * port["수량"]
port["수익률(%)"] = ((port["현재가"] - port["매수가"]) / port["매수가"] * 100).round(2)
port
```

</details>

In [ ]:
# 코드 입력

# STEP 2. 컬럼 계산 — 평가금액, 수익금, 수익률(%)
port["평가금액"] = port["현재가"] * port["수량"]
port["수익금"]  = (port["현재가"] - port["매수가"]) * port["수량"]
port["수익률(%)"] = ((port["현재가"] - port["매수가"]) / port["매수가"] * 100).round(2)
port


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# STEP 3. np.where로 상태 라벨 붙이기
port["상태"] = np.where(port["수익금"] > 0, "수익", "손실")
port
```

</details>

In [ ]:
# 코드 입력

# STEP 3. np.where로 상태 라벨 붙이기
port["상태"] = np.where(port["수익금"] > 0, "수익", "손실")
port


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# STEP 4. 질문에 답하기 — 조건 선택, 통계, idxmax
print("수익 중인 종목만:")
print(port[port["수익금"] > 0])

print("\n총 평가금액:", port["평가금액"].sum())
print("평균 수익률(%):", port["수익률(%)"].mean().round(2))

best = port["평가금액"].idxmax()
print("평가금액 1위 종목:", port.loc[best, "종목"])
```

</details>

In [ ]:
# 코드 입력

# STEP 4. 질문에 답하기 — 조건 선택, 통계, idxmax
print("수익 중인 종목만:")
print(port[port["수익금"] > 0])

print("\n총 평가금액:", port["평가금액"].sum())
print("평균 수익률(%):", port["수익률(%)"].mean().round(2))

best = port["평가금액"].idxmax()
print("평가금액 1위 종목:", port.loc[best, "종목"])


<details>
<summary> ---------- 💡 예시 코드 보기 ---------- </summary>

```python
# STEP 5. 수익률 순으로 줄 세우기 (sort_values)
port.sort_values("수익률(%)", ascending=False)
```

</details>

In [ ]:
# 코드 입력

# STEP 5. 수익률 순으로 줄 세우기 (sort_values)
port.sort_values("수익률(%)", ascending=False)


> 💡 방금 한 5단계(표 생성 → 컬럼 계산 → 라벨 → 조건/통계 질문 → 정렬)가 데이터 분석의 가장 기본적인 한 사이클입니다.
> 다음 시간(CH07)부터는 실제 파일(CSV)을 불러와서, 더 크고 지저분한 데이터에 오늘의 기본기를 확장 적용합니다.

## 🎉 정규 수업 완료!

수고하셨습니다. 🌙 자율 멘토링 시간에는 각 챕터의 💻 실습(TODO)과 📝 실습 과제를 직접 풀어보세요.
